// SPDX-License-Identifier: GPL-2.0-only

/*
 * Copyright (C) 2024 Enjellic Systems Development, LLC
 * Author: Dr. Greg Wettstein <greg@enjellic.com>
 *
 * This file contains methods and definitions for the 'model0'
 * security model implementation.  This is the default model that
 * TSEM implements.
 */

#include "tsem.h"

static bool event_handlers[TSEM_EVENT_CNT] = {
	[TSEM_BPRM_COMMITTED_CREDS] = true,
	[TSEM_TASK_KILL] = true,
	[TSEM_TASK_SETPGID] = true,
	[TSEM_TASK_GETPGID] = true,
	[TSEM_TASK_GETSID] = true,
	[TSEM_TASK_SETNICE] = true,
	[TSEM_TASK_SETIOPRIO] = true,
	[TSEM_TASK_GETIOPRIO] = true,
	[TSEM_TASK_PRLIMIT] = true,
	[TSEM_TASK_SETRLIMIT] = true,
	[TSEM_TASK_SETSCHEDULER] = true,
	[TSEM_TASK_GETSCHEDULER] = true,
	[TSEM_TASK_PRCTL] = true,
	[TSEM_FILE_OPEN] = true,
	[TSEM_MMAP_FILE] = true,
	[TSEM_FILE_IOCTL] = true,
	[TSEM_FILE_LOCK] = true,
	[TSEM_FILE_FCNTL] = true,
	[TSEM_FILE_RECEIVE] = true,
	[TSEM_UNIX_STREAM_CONNECT] = true,
	[TSEM_UNIX_MAY_SEND] = true,
	[TSEM_SOCKET_CREATE] = true,
	[TSEM_SOCKET_CONNECT] = true,
	[TSEM_SOCKET_BIND] = true,
	[TSEM_SOCKET_ACCEPT] = true,
	[TSEM_SOCKET_LISTEN] = true,
	[TSEM_SOCKET_SOCKETPAIR] = true,
	[TSEM_SOCKET_SENDMSG] = true,
	[TSEM_SOCKET_RECVMSG] = true,
	[TSEM_SOCKET_GETSOCKNAME] = true,
	[TSEM_SOCKET_GETPEERNAME] = true,
	[TSEM_SOCKET_SETSOCKOPT] = true,
	[TSEM_SOCKET_SHUTDOWN] = true,
	[TSEM_PTRACE_TRACEME] = true,
	[TSEM_KERNEL_MODULE_REQUEST] = true,
	[TSEM_KERNEL_LOAD_DATA] = true,
	[TSEM_KERNEL_READ_FILE] = true,
	[TSEM_SB_MOUNT] = true,
	[TSEM_SB_UMOUNT] = true,
	[TSEM_SB_REMOUNT] = true,
	[TSEM_SB_PIVOTROOT] = true,
	[TSEM_SB_STATFS] = true,
	[TSEM_MOVE_MOUNT] = true,
	[TSEM_SHM_ASSOCIATE] = true,
	[TSEM_SHM_SHMCTL] = true,
	[TSEM_SHM_SHMAT] = true,
	[TSEM_SEM_ASSOCIATE] = true,
	[TSEM_SEM_SEMCTL] = true,
	[TSEM_SEM_SEMOP] = true,
	[TSEM_SYSLOG] = true,
	[TSEM_SETTIME] = true,
	[TSEM_QUOTACTL] = true,
	[TSEM_QUOTA_ON] = true,
	[TSEM_MSG_QUEUE_ASSOCIATE] = true,
	[TSEM_MSG_QUEUE_MSGCTL] = true,
	[TSEM_MSG_QUEUE_MSGSND] = true,
	[TSEM_MSG_QUEUE_MSGRCV] = true,
	[TSEM_IPC_PERMISSION] = true,
	[TSEM_KEY_ALLOC] = true,
	[TSEM_KEY_PERMISSION] = true,
	[TSEM_NETLINK_SEND] = true,
	[TSEM_INODE_CREATE] = true,
	[TSEM_INODE_LINK] = true,
	[TSEM_INODE_UNLINK] = true,
	[TSEM_INODE_SYMLINK] = true,
	[TSEM_INODE_MKDIR] = true,
	[TSEM_INODE_RMDIR] = true,
	[TSEM_INODE_MKNOD] = true,
	[TSEM_INODE_RENAME] = true,
	[TSEM_INODE_SETATTR] = true,
	[TSEM_INODE_GETATTR] = true,
	[TSEM_INODE_SETXATTR] = true,
	[TSEM_INODE_GETXATTR] = true,
	[TSEM_INODE_LISTXATTR] = true,
	[TSEM_INODE_REMOVEXATTR] = true,
	[TSEM_INODE_KILLPRIV] = true,
	[TSEM_TUN_DEV_CREATE] = true,
	[TSEM_TUN_DEV_ATTACH_QUEUE] = true,
	[TSEM_TUN_DEV_ATTACH] = true,
	[TSEM_TUN_DEV_OPEN] = true,
	[TSEM_BPF] = true,
	[TSEM_BPF_MAP] = true,
	[TSEM_BPF_PROG] = true,
	[TSEM_PTRACE_ACCESS_CHECK] = true,
	[TSEM_CAPABLE] = true,
	[TSEM_CAPGET] = true,
	[TSEM_CAPSET] = true,
	[TSEM_TASK_ALLOC] = true,
	[TSEM_TASK_FREE] = true
};

const struct tsem_context_ops tsem_model0_ops = {
	.name = "model0",
	.events = event_handlers,
	.generate = tsem_event_generate,
	.map = tsem_map_event
};
